apiVersion: v2
description: Servarr service deployment 
name: servarr
type: application
version: "0.0.1"
appVersion: "0.0.1"
keywords:
  - sonarr
  - radarr
  - readarr
  - prowlarr
  - bazarr
  - servarr
maintainers:
  - name: Alexandre Delisle
    email: alexodelisle@gmail.com
dependencies:
  - name: eos-secret-store
    version: "0.0.2"
    repository: "oci://ghcr.io/alexandreodelisle"
    condition: eos-secret-store.enabled
  - name: cloudnative-pg
    version: "v0.26.0"
    repository: "https://cloudnative-pg.github.io/charts"
    condition: cnpg.enabled
  - name: openebs
    version: "4.3.2"
    repository: "https://openebs.github.io/openebs"
    condition: openebs.enabled