volumeMounts:
  - name: libraries
    mountPath: /tv
    subPath: series
  - name: libraries
    mountPath: /movies
    subPath: movies
  - name: libraries
    mountPath: /books
    subPath: books
  - name: downloads
    mountPath: /downloads
global:
  permissions:
    PUID: 1030
    PGID: 1000
  network:
    domain: mydomain.com
    expose: 
      type: route # options: ingress, route, none
      gateway:
        name: cilium-gateway
        namespace: kube-system
      
services:
  sonarr:
    enabled: true
    image: lscr.io/linuxserver/sonarr
    tag: 4.0.15
    containerPort: 8989
    postgresql:
      enabled: true
      username: sonarr
      secretRef: sonarr-db-secret
  radarr:
    enabled: true
    image: lscr.io/linuxserver/radarr
    tag: 5.26.2
    containerPort: 7878
    postgresql:
      enabled: true
      username: radarr
      secretRef: radarr-db-secret
  readarr:
    enabled: true
    image: lscr.io/linuxserver/readarr
    tag: 0.3.22-nightly
    containerPort: 8787
    postgresql:
      enabled: true
      username: readarr
      secretRef: readarr-db-secret
  prowlarr:
    enabled: true
    image: lscr.io/linuxserver/prowlarr
    tag: 1.37.0
    containerPort: 9696
    postgresql:
      enabled: true
      username: prowlarr
      secretRef: prowlarr-db-secret
  bazarr:
    enabled: true
    image: lscr.io/linuxserver/bazarr
    tag: v1.4.3-ls264
    containerPort: 6767
    postgresql:
      enabled: true
      username: bazarr
      secretRef: bazarr-db-secret
storage:
  nfs:
    IPAddress: 10.0.0.0
  mounts:
    libraries:
      storage: 800Gi
      storageClaim: 250Gi
      accessModes: [ReadWriteMany]
      path: "/volume1/kubernetes/libraries"
    configs:
      storage: 800Gi
      storageClaim: 250Gi
      accessModes: [ReadWriteMany]
      path: "/volume1/kubernetes/configs/staging"
    downloads:
      storage: 800Gi
      storageClaim: 250Gi
      accessModes: [ReadWriteMany]
      path: "/volume1/kubernetes/downloads"