{{- range $service, $config := .Values.services }}
{{ if or $config.postgres.enabled | default $.Values.global.postgres.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $service }}-db
  labels: 
    cnpg.io/cluster:  {{ $service }}-db
spec:
  instances: 1
  storage:
    storageClass: openebs-hostpath
    size: 5Gi
  bootstrap:
    initdb:
      database: main
      owner: {{ $config.postgres.username }}
      dataChecksums: true
      postInitSQL:
        - "CREATE DATABASE \"{{ $service }}-log\";"
        - "CREATE DATABASE \"{{ $service }}-main\";"
        - "CREATE DATABASE \"{{ $service }}-cache\";"
        - "ALTER DATABASE \"{{ $service }}-main\" OWNER TO {{ $config.postgres.username }};"
        - "ALTER DATABASE \"{{ $service }}-log\" OWNER TO {{ $config.postgres.username }};"
        - "ALTER DATABASE \"{{ $service }}-cache\" OWNER TO {{ $config.postgres.username }};"
      secret:
        name: {{ $config.postgres.secretRef }}  
  monitoring:
    enablePodMonitor: true
{{ end }}
{{- end }}