{{- range $service, $config := .Values.services }}
{{ if $config.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
 name: {{ $config.postgresql.password.secretRef }}
 namespace: {{ .Release.Namespace }}
data:
    username: {{ default $config.postgresql.username $config.postgresql.username | b64enc | quote }}
    password: {{ default $config.postgresql.password $config.postgresql.password | b64enc | quote }}
{{ end }}
{{- end }}